server:
  port: ${PORT:8080}
  tomcat:
    threads:
      max: 50

spring:
  jackson:
    serialization:
      write-dates-as-timestamps: false

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 110MB
  jpa:
    properties:
      hibernate:
        ddl-auto: update
        show_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
      temp:
        use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: update

  application:
    name: RepairKZ-Backend
security:
  key: ${JWT_SECRET}
logging:
  level:
    org.springframework.web: INFO
    root: INFO
mailersend:
  api-key: ${RESEND_API_KEY}